---
title: "Can we predict house prices using known features of each house and a supervised learning approach?"
author: "Florence Galliers"
date: "18/10/2020"
output: 
  pdf_document:
    toc: true #table of contents true, default depth 3
    number_sections: true
    df_print: kable
---
```{r, set wd / libraries / reading in data, include = FALSE}
setwd("~/Google Drive/Harper/1-C7081/Asssesment/github-C7081/C7081-assessment")

library(knitr)
library(ggplot2)
library(glmnet)
library(pls)
library(leaps)
library(tree)
library(randomForest)
library(gbm)


data <- read.csv(file = "original-data.csv")
```


# Background:


## Objectives:


# Data:


## Data Preparation:


```{r, echo = FALSE}

```

The remaining variables and their descriptions are shown in Table 1:

```{r, Table 1, echo = FALSE}

#insert table 1
data_descriptions <- c("House sale price in thousands of US dollars", 
                       "Number of bedrooms",
                       "Number of bathrooms",
                       "Area of house in square feet",
                       "Area of whole housing lot in square feet",
                       "Number of floors in the house",
                       "Condition of house, 1 to 5",
                       "1 = if house has a basement, 0 = no basement",
                       "Year that the house was built subtracted from 2014",
                       "1 = if house has been renovated, 0 = if no renovation",
                       "Location of house to the nearest city in Washington, USA")

data_dictionary <- data.frame(names(data), data_descriptions)

kable(data_dictionary,
      col.names = c("Variable", "Description"),
      caption = "Data Dictionary")

```


# Methods:

```{r, splitting into training and test set}

set.seed(2) 
n = nrow(data2) #number of rows
train_index = sample(1:n, size = round(0.8*n), replace=FALSE) 
train = data2[train_index ,] #takes 80% of the data for training set
test = data2[-train_index ,] #remaining 20% for the test set

```

```{r, least squares}
lm_model <- lm(price ~ ., 
               data = train)
# make predictions on test set
lm_pred <- predict(lm_model, test) 
# calculate MSE
mean((test[, "price"] - lm_pred)^2)
summary(lm_model)

# Diagnostic plots of the linear regression model
par(mfrow=c(2,2))
plot(lm_model)

```

```{r, include = FALSE}

```

```{r, trees, include = FALSE}

```



```{r, include=FALSE}


```

# Results:


## Conclusions:



# References
